### ISSUE TITLE
Parse empty string as nil

### ISSUE THREAD

**Issue by DanielZendejas** [joshdholtz/ecto-lazy-float#1]
Hey, I had the use case where the front end might send an empty string for a numeric value.

I forked your project [and added one line](https://github.com/DanielZendejas/ecto-lazy-float/blob/master/lib/lazy_float.ex#L5) that would allow it to parse the empty string as nil.

Do you think this is a common scenario? If you like it then I could make a PR for this small change.

**Comment by joshdholtz** [comment]
@DanielZendejas If you want to make a PR that would be great!

**Comment by nickgartmann** [comment]
I would suggest

```elixir
def cast(""), do: {:ok, nil}
```
as being a bit more idiomatic elixir, since you're testing for the special case of `""`

**Comment by DanielZendejas** [comment]
Cool, the PR is now in https://github.com/joshdholtz/ecto-lazy-float/pull/2 .
